### ISSUE TITLE
Far future request: Rename GoboHide to filesystem

### ISSUE THREAD

**Issue by BoQsc** [gobolinux/GoboHide#3]
I really like the playful GoboHide name for this project. But I'd like to see a preparation for better name that is more systemic, robust and better that could merge in the documentation and would not require additional out of technical-context name.

I'd go for Gobo `filesystem` instead of  `gobohide`.

Example:
`filesystem --list-hidden-directories`  
instead of `gobohide -l` would be great improvement.

**Comment by lucasvr** [comment]
Thanks for opening up a suggestion, but I don't see how `filesystem` is a better choice. It's actually worse, because there are just so many possible filesystem operations ("format", "locate", "id", etc) that you'd end up needing to rename the whole programs from coreutils. We'll keep using gobohide for the foreseeable future.
